### ISSUE TITLE
[runtime] Error: failed to register new resource website [gcp-scaffold:index:project]: Resource monitor is terminating

### ISSUE THREAD

**Issue by simenandre** [cobraz/pulumi-gcp-scaffold#3]
**Describe the bug**
When running `pulumi up` with @cobraz/pulumi-gcp-scaffold v0.3.0 it fails with the following error:

```
pulumi:pulumi:Stack infra-core-prod running error: [runtime] Error: failed to register new resource website [gcp-scaffold:index:project]: Resource monitor is terminating
      pulumi:pulumi:Stack infra-core-prod running     at Object.registerResource (/home/runner/work/infra/infra/node_modules/@pulumi/pulumi/runtime/resource.js:219:27)
      pulumi:pulumi:Stack infra-core-prod running     at new Resource (/home/runner/work/infra/infra/node_modules/@pulumi/pulumi/resource.js:215:24)
      pulumi:pulumi:Stack infra-core-prod running     at new ComponentResource (/home/runner/work/infra/infra/node_modules/@pulumi/pulumi/resource.js:386:9)
      pulumi:pulumi:Stack infra-core-prod running     at new Project (/home/runner/work/infra/infra/node_modules/@cobraz/project.ts:58:9)
      pulumi:pulumi:Stack infra-core-prod running     at Object.<anonymous> (/home/runner/work/infra/infra/resources/website/google/project.ts:6:31)
      pulumi:pulumi:Stack infra-core-prod running     at Module._compile (internal/modules/cjs/loader.js:1068:30)
      pulumi:pulumi:Stack infra-core-prod running     at Module.m._compile (/home/runner/work/infra/infra/node_modules/ts-node/src/index.ts:439:23)
      pulumi:pulumi:Stack infra-core-prod running     at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
      pulumi:pulumi:Stack infra-core-prod running     at Object.require.extensions.<computed> [as .ts] (/home/runner/work/infra/infra/node_modules/ts-node/src/index.ts:442:12)
      pulumi:pulumi:Stack infra-core-prod running     at Module.load (internal/modules/cjs/loader.js:933:32)
 ```

See failed run: https://github.com/ayrorg/infra/runs/2868538593?check_suite_focus=true

**To Reproduce**

See actual repository here: https://github.com/ayrorg/infra

**Expected behavior**

I expected the project to be created and the APIs enabled like described here: https://github.com/ayrorg/infra/blob/main/resources/website/google/project.ts

**Comment by stack72** [comment]
What version of NodeJS are you using? 16.x per chance?

**Comment by simenandre** [comment]
14.x AFAIK. I can add a setup-node step to ensure 👍
